using System;
using System.Collections.Generic;

namespace StandardApp.Models
{
    public partial class CustVendorMaster
    {
        public string CustVendorMasterId { get; set; }
        public string CustVendor { get; set; }
        public string CustVendorCode { get; set; }
        public string CustVendorName { get; set; }
        public string ShortName { get; set; }
        public string CustVendorType { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string PaymentTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string City { get; set; }
        public string CurrencyMasterId { get; set; }
        public string Country { get; set; }
        public string Pin { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Cat { get; set; }
        public decimal? CreditLimit { get; set; }
        public decimal? CreditDays { get; set; }
        public string CreditTerms { get; set; }
        public decimal? CommPer { get; set; }
        public DateTime? CommFrom { get; set; }
        public DateTime? CommTo { get; set; }
        public string Currency { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string Cstno { get; set; }
        public string Mstno { get; set; }
        public string Eccno { get; set; }
        public string ExDivi { get; set; }
        public string ExRange { get; set; }
        public string CountryId { get; set; }
        public bool? Active { get; set; }
        public string InspectionBody { get; set; }
        public string RemittanceInstruction { get; set; }
        public string State { get; set; }
        public string Panno { get; set; }
        public string ServiceTaxNo { get; set; }
        public string EnterpriseType { get; set; }
        public decimal? CreationLevel { get; set; }
        public decimal? UserLevel { get; set; }
        public string IsDeleted { get; set; }
        public string AddedBy { get; set; }
        public DateTime? AddedDt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDt { get; set; }
        public string AccountId { get; set; }
        public string PayeeName { get; set; }
        public string Oms { get; set; }
        public string EntityGroupMasterId { get; set; }
        public string Typeofservices { get; set; }
        public string IsForeign { get; set; }
        public string Crmcode { get; set; }
        public string EntityClass { get; set; }
        public string SystemUserId { get; set; }
        public decimal? CommRate { get; set; }
        public string ExtnlSysRef1 { get; set; }
        public string ExtnlSysRef2 { get; set; }
        public string ExtnlSysRef3 { get; set; }
        public string Ifscode { get; set; }
        public string Branch { get; set; }
        public string AccountType { get; set; }
        public string AccountNo { get; set; }
        public string RegistrationFormNo { get; set; }
        public bool? IsSalesEngr { get; set; }
        public string TaxClass { get; set; }
        public string ServClId { get; set; }
        public string SlCatId { get; set; }
        public string EnpndPo { get; set; }
        public string Engrn { get; set; }
        public string Enpymt { get; set; }
        public string Eninv { get; set; }
        public string Enrect { get; set; }
        public string Tanno { get; set; }
        public string PriceListId { get; set; }
        public bool? IsApproved { get; set; }
        public DateTime? EvaluationDt { get; set; }
        public string ResellerName { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public bool? IsActive { get; set; }
        public string IsWlforCrmref { get; set; }
        public DateTime? EntityRestDate { get; set; }
        public string FkbusiSegmentId { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Taluka { get; set; }
        public string District { get; set; }
        public string Website { get; set; }
        public string CopyofCustVendorName { get; set; }
        public string IsContractReqd { get; set; }
        public string VendorCode { get; set; }
        public string AadharNo { get; set; }
        public string EsicNo { get; set; }
        public string Pfno { get; set; }
        public string Cin { get; set; }
        public string TenorYear { get; set; }
        public string IndIndemnity { get; set; }
        public string GroupId { get; set; }
    }
}
