using System;
using System.Collections.Generic;

namespace StandardApp.Models
{
    public partial class ItemPlant
    {
        public string ItemPlantId { get; set; }
        public string PlantId { get; set; }
        public string ItemMasterId { get; set; }
        public string PurUnit { get; set; }
        public string SalesUnit { get; set; }
        public string StockUnit { get; set; }
        public string Pscunit { get; set; }
        public string SecUnit { get; set; }
        public string UnitRateOn { get; set; }
        public decimal? RateFactor { get; set; }
        public decimal? Convfactor { get; set; }
        public string WareHouseMasterId { get; set; }
        public string LocationMasterId { get; set; }
        public decimal? ShelfLife { get; set; }
        public bool? SuspendedForTransactions { get; set; }
        public DateTime? SuspendedForTransactionsDate { get; set; }
        public bool? AllowNegativeStock { get; set; }
        public bool? BatchControl { get; set; }
        public decimal? Ohqty { get; set; }
        public decimal? Sohqty { get; set; }
        public decimal? AvgCost { get; set; }
        public decimal? MinStock { get; set; }
        public decimal? MaxStock { get; set; }
        public decimal? Eoq { get; set; }
        public decimal? ReorderLevel { get; set; }
        public decimal? SafetyStock { get; set; }
        public string PlannerId { get; set; }
        public string OrderPolicy { get; set; }
        public string AlternateItem { get; set; }
        public string Abcclass { get; set; }
        public decimal? PurLeadTimeAdmin { get; set; }
        public decimal? PurLeadTimeVendor { get; set; }
        public decimal? PurLeadTimeSafety { get; set; }
        public string BuyerId { get; set; }
        public bool? SuspendedForOrders { get; set; }
        public DateTime? SuspendedForOrdersDate { get; set; }
        public string PrimaryVendor { get; set; }
        public string ExMainHdgNo { get; set; }
        public string ExSubHdgNo { get; set; }
        public string PtaxCode { get; set; }
        public string StaxCode { get; set; }
        public string PurAccNo { get; set; }
        public string SaleAccNo { get; set; }
        public decimal? PurchaseRate { get; set; }
        public bool? InspOnRect { get; set; }
        public bool? IndentReqd { get; set; }
        public bool? ContractReqd { get; set; }
        public string LandedCostFactorId { get; set; }
        public decimal? StdCost { get; set; }
        public decimal? StdCostMaterial { get; set; }
        public decimal? StdCostOh { get; set; }
        public decimal? FutureCost { get; set; }
        public decimal? FutureCostMaterial { get; set; }
        public decimal? FutureCostOh { get; set; }
        public decimal? StdPurMtrlCost { get; set; }
        public decimal? FuturePurMtrlCost { get; set; }
        public decimal? StdMfgMtrlCost { get; set; }
        public decimal? FutureMfgMtrlCost { get; set; }
        public decimal? StdProcessRunCost { get; set; }
        public decimal? FutureProcessRunCost { get; set; }
        public decimal? StdProcessSetupCost { get; set; }
        public decimal? FutureProcessSetupCost { get; set; }
        public decimal? StdScrapRealization { get; set; }
        public decimal? FutureScrapRealization { get; set; }
        public decimal? LotSize { get; set; }
        public string GrossWt { get; set; }
        public decimal? NetWt { get; set; }
        public string PackingCode { get; set; }
        public string ContainerCode { get; set; }
        public decimal? QtyInContainer { get; set; }
        public string PanCosting { get; set; }
        public string PanFinance { get; set; }
        public string PanPlanning { get; set; }
        public string PanShipping { get; set; }
        public string PanStocking { get; set; }
        public string PanUom { get; set; }
        public decimal? CreationLevel { get; set; }
        public decimal? UserLevel { get; set; }
        public string IsDeleted { get; set; }
        public string AddedBy { get; set; }
        public DateTime? AddedDt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDt { get; set; }
        public decimal? AssableRate { get; set; }
        public decimal? TarrifDuty { get; set; }
        public bool? Active { get; set; }
        public string RejLocationMasterId { get; set; }
        public string Manufactured { get; set; }
        public string ItemSalesGroupId { get; set; }
        public decimal? FinalCost { get; set; }
        public bool? Rfqreqd { get; set; }
        public decimal? ShipngLdTm { get; set; }
        public string IssueOnMo { get; set; }
        public string IssueOnMrs { get; set; }
        public decimal? AssessableRate { get; set; }
        public decimal? AssessablePercent { get; set; }
        public string TaxInRegion { get; set; }
        public string TaxOutRegion { get; set; }
        public decimal? SalesRateInRegion { get; set; }
        public decimal? SalesRateOutRegion { get; set; }
        public decimal? MrpinRegion { get; set; }
        public decimal? MrpoutRegion { get; set; }
        public string IsPacketAppl { get; set; }
        public decimal? StdWt { get; set; }
        public decimal? StdPccardQty { get; set; }
        public decimal? WtdAvgRate { get; set; }
        public decimal? WtdAvgValue { get; set; }
        public string ExciseHeadingId { get; set; }
        public string FamilyId { get; set; }
        public bool? EngineeredToOrder { get; set; }
        public decimal? ToolLife { get; set; }
        public bool? AllowExcessQtyGrn { get; set; }
        public decimal? PerExcessAllowGrn { get; set; }
        public bool? IsQtyperbox { get; set; }
        public decimal? Qtyperbox { get; set; }
        public decimal? StdCft { get; set; }
        public decimal? StdWeight { get; set; }
        public decimal? ReceivingLeadTime { get; set; }
        public decimal? TransitLeadtime { get; set; }
        public bool? ExpiryApplicable { get; set; }
        public decimal? SupplyDays { get; set; }
        public decimal? MultiplesOf { get; set; }
        public string ItemPurchaseGroupId { get; set; }
        public bool? IsSubcontracted { get; set; }
        public bool? IsVerAppl { get; set; }
        public string NoofHu { get; set; }
        public decimal? Lbhlength { get; set; }
        public decimal? Lbhbreadth { get; set; }
        public decimal? Lbhheight { get; set; }
        public DateTime? LastPidate { get; set; }
        public string FifoControl { get; set; }
        public decimal? Volume { get; set; }
    }
}
