using System;
using System.Collections.Generic;

namespace StandardApp.Models
{
    public partial class SalesHeader
    {
        public string SalesHeaderId { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDt { get; set; }
        public string CustomerId { get; set; }
        public string SalesOrderHeaderId { get; set; }
        public string CustomerPono { get; set; }
        public DateTime? CustomerPodt { get; set; }
        public string DcmainId { get; set; }
        public decimal? InvoiceTypeMasterId { get; set; }
        public string TransMode { get; set; }
        public string TransName { get; set; }
        public string LorryNo { get; set; }
        public DateTime? RemovalDt { get; set; }
        public decimal? SaleAmt { get; set; }
        public decimal? AsseblVal { get; set; }
        public string Remark { get; set; }
        public bool? Printed { get; set; }
        public decimal? DiscAmt { get; set; }
        public decimal? RoundOff { get; set; }
        public decimal? RecdAmt { get; set; }
        public bool? CashCredit { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public decimal? TotQty { get; set; }
        public string Lcno { get; set; }
        public string Notes { get; set; }
        public decimal? MaterialVal { get; set; }
        public decimal? AgentCode { get; set; }
        public string InvoiceGroup { get; set; }
        public decimal? PayTermId { get; set; }
        public decimal? ChqNo { get; set; }
        public string ChqBank { get; set; }
        public DateTime? ChqDate { get; set; }
        public decimal? CashRecd { get; set; }
        public decimal? ChqAmt { get; set; }
        public string SaleType { get; set; }
        public decimal? MarkupAmt { get; set; }
        public decimal? MarginAmt { get; set; }
        public string Lrno { get; set; }
        public DateTime? Lrdt { get; set; }
        public decimal? Lrpacks { get; set; }
        public decimal? Lrfreight { get; set; }
        public decimal? CashDisc { get; set; }
        public decimal? SalesRetAmt { get; set; }
        public decimal? InsuAmt { get; set; }
        public decimal? Mrptot { get; set; }
        public decimal? CreationLevel { get; set; }
        public decimal? UserLevel { get; set; }
        public string IsDeleted { get; set; }
        public string AddedBy { get; set; }
        public DateTime? AddedDt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDt { get; set; }
        public string PlantMasterId { get; set; }
        public string StatusId { get; set; }
        public string DeleDestination { get; set; }
        public string DeleConsigneeName { get; set; }
        public string DeleAddress { get; set; }
        public string DeleCity { get; set; }
        public string DeleState { get; set; }
        public string DeleCountry { get; set; }
        public string DelePhone { get; set; }
        public string DeleFax { get; set; }
        public string DeleMobile { get; set; }
        public string DeleContactPerson { get; set; }
        public string DeleAwbno { get; set; }
        public string DeleTransporter { get; set; }
        public string DeleTransporterAddress { get; set; }
        public string DeleForwarder { get; set; }
        public string DeleInsuranceCompany { get; set; }
        public string ConsDestination { get; set; }
        public string ConsConsigneeName { get; set; }
        public string ConsAddress { get; set; }
        public string ConsCity { get; set; }
        public string ConsState { get; set; }
        public string ConsCountry { get; set; }
        public string ConsPhone { get; set; }
        public string ConsFax { get; set; }
        public string ConsMobile { get; set; }
        public string ConsContactPerson { get; set; }
        public string ConsAwbno { get; set; }
        public string ConsTransporter { get; set; }
        public string ConsTransporterAddress { get; set; }
        public string ConsForwarder { get; set; }
        public string ConsInsuranceCompany { get; set; }
        public string DispatchNo { get; set; }
        public DateTime? Dispatchdt { get; set; }
        public string RecordTypeId { get; set; }
        public decimal? TotalCartonQty { get; set; }
        public decimal? TotalCbm { get; set; }
        public decimal? TotalQtyinDozen { get; set; }
        public DateTime? Effdate { get; set; }
        public string Bolno { get; set; }
        public DateTime? Boldate { get; set; }
        public decimal? TotGrossAmnt { get; set; }
        public decimal? TotTaxAmnt { get; set; }
        public decimal? DiscPer { get; set; }
        public decimal? TotNetAmnt { get; set; }
        public string OrderTypeId { get; set; }
        public string ShipToMasterId { get; set; }
        public string DeliveryMode { get; set; }
        public string FreightPayMode { get; set; }
        public decimal? BasicAmnt { get; set; }
        public decimal? ChargeAmnt { get; set; }
        public decimal? BasicTaxAmnt { get; set; }
        public decimal? ChargeTaxAmnt { get; set; }
        public string DocType { get; set; }
        public string BillToId { get; set; }
        public string PikPakStatusId { get; set; }
        public decimal? ExRate { get; set; }
        public decimal? BasicAmtFc { get; set; }
        public decimal? TotTaxAmtFc { get; set; }
        public decimal? TotChargeAmtFc { get; set; }
        public decimal? TotDiscAmtFc { get; set; }
        public decimal? NetAmtFc { get; set; }
        public decimal? TotGrossAmntFc { get; set; }
        public decimal? BasicTaxAmntFc { get; set; }
        public decimal? ChargeTaxAmntFc { get; set; }
        public string MainfestId { get; set; }
        public string MainfestNo { get; set; }
        public string Podrecd { get; set; }
        public string BankSwiftCode { get; set; }
        public DateTime? VehicleInTime { get; set; }
        public DateTime? VehicleOutTime { get; set; }
        public DateTime? DockInTime { get; set; }
        public DateTime? DockOutTime { get; set; }
        public string GrossWt { get; set; }
        public string Netwt { get; set; }
        public string Shipper { get; set; }
        public string ChallanNo { get; set; }
        public string SealNo { get; set; }
        public string Soheaderid { get; set; }
        public string ShipStatus { get; set; }
        public string TatReasonId { get; set; }
        public string TatRemark { get; set; }
        public string FinalInvoiceNo { get; set; }
        public string ActivityId { get; set; }
        public DateTime? DeliveryDate { get; set; }
    }
}
