using System;
using System.Collections.Generic;

namespace StandardApp.Models
{
    public partial class TransHeader
    {
        public decimal? RecId { get; set; }
        public string TransHeaderId { get; set; }
        public string VouMasterId { get; set; }
        public string FinDivId { get; set; }
        public string TransNo { get; set; }
        public string TransType { get; set; }
        public string TransGlid { get; set; }
        public DateTime? DocDate { get; set; }
        public DateTime? EffDate { get; set; }
        public DateTime? SupplyDate { get; set; }
        public string PeriodMasterId { get; set; }
        public decimal? PeriodDisplaySeq { get; set; }
        public string OmitPeriodAccural { get; set; }
        public string PartyId { get; set; }
        public string PartyName { get; set; }
        public string TransEntity { get; set; }
        public string TransAccType { get; set; }
        public string IdTradingPartnerId { get; set; }
        public string IdRefNo { get; set; }
        public string JournalTypePosted { get; set; }
        public string JournalNoPosted { get; set; }
        public string JournalNoReassign { get; set; }
        public string JournalTypeReassign { get; set; }
        public string TaxTransType { get; set; }
        public string TheirRef { get; set; }
        public string BillInvNo { get; set; }
        public DateTime? BillInvDate { get; set; }
        public string Boeno { get; set; }
        public DateTime? Boedate { get; set; }
        public string Lcno { get; set; }
        public DateTime? Lcdate { get; set; }
        public string FwdCvrNo { get; set; }
        public DateTime? FwdCvrDt { get; set; }
        public string InwRemNo { get; set; }
        public string TransContact { get; set; }
        public string ShipToId { get; set; }
        public string ShipToRef { get; set; }
        public string ApplyTax { get; set; }
        public string Contingentliability { get; set; }
        public decimal? PersonalLgrValue { get; set; }
        public decimal? PersonalLgrValueFc { get; set; }
        public decimal? CashValue { get; set; }
        public decimal? CashValueFc { get; set; }
        public decimal? LinesValue { get; set; }
        public decimal? LinesValueFc { get; set; }
        public decimal? Glvalue { get; set; }
        public decimal? GlvalueFc { get; set; }
        public decimal? AllocationBal { get; set; }
        public decimal? AllocationBalFc { get; set; }
        public decimal? SettlementBal { get; set; }
        public decimal? SettlementBalFc { get; set; }
        public decimal? TaxValue { get; set; }
        public decimal? TaxValueFc { get; set; }
        public string CurrencyId { get; set; }
        public decimal? ExRate { get; set; }
        public decimal? MultiDivider { get; set; }
        public decimal? ExRateOverride { get; set; }
        public string BatchId { get; set; }
        public string OriginUnit { get; set; }
        public string OriginUser { get; set; }
        public string ApportionMasterId { get; set; }
        public string TransSource { get; set; }
        public decimal? LastLineNo { get; set; }
        public decimal? LastAttLineNo { get; set; }
        public string TransNarrative { get; set; }
        public string TransStatus { get; set; }
        public string IsTransPosted { get; set; }
        public string IsTransInUse { get; set; }
        public string UnpostedAlloc { get; set; }
        public string IsRepeatingTrans { get; set; }
        public string IgnoreWarnings { get; set; }
        public string ArchiveStatus { get; set; }
        public string TransApprovalStatus { get; set; }
        public string IsOneTimeAccTrans { get; set; }
        public string LastChgFromSys { get; set; }
        public string NarrativeId { get; set; }
        public string InstallMethodId { get; set; }
        public string NoteMethodId { get; set; }
        public string NoteTransNo { get; set; }
        public DateTime? NoteDueDt { get; set; }
        public string WithholdingMethodId { get; set; }
        public string PocurrencyId { get; set; }
        public decimal? PoexRate { get; set; }
        public decimal? PomultiDivider { get; set; }
        public decimal? PoexRateOverride { get; set; }
        public string PostingSeqNo { get; set; }
        public decimal? SettlementVal { get; set; }
        public decimal? SettlementValFc { get; set; }
        public decimal? SettlementBalOs { get; set; }
        public string GlpostingTrans { get; set; }
        public string DisputedTransaction { get; set; }
        public string DisputeReason { get; set; }
        public string PaymentSttlTermsId { get; set; }
        public string PayeeName { get; set; }
        public string RefTransHeaderId { get; set; }
        public string RefTransHeaderType { get; set; }
        public string RefTransHeaderInfo { get; set; }
        public string GateEntryNo { get; set; }
        public DateTime? GateEntryDt { get; set; }
        public string CapexFormMasterId { get; set; }
        public string IsDeleted { get; set; }
        public string SecId { get; set; }
        public string AddedBy { get; set; }
        public DateTime? AddedDt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDt { get; set; }
        public string SalesEngg { get; set; }
        public string IsTemplate { get; set; }
        public decimal? AmtDistributed { get; set; }
        public string EntityId { get; set; }
        public string SourceType { get; set; }
        public string SourceId { get; set; }
        public string RecurrHeaderId { get; set; }
    }
}
